### ISSUE TITLE
vita-bootanim issues

### ISSUE THREAD

**Issue by EntireCircus** [SKGleba/VitaTools#2]
multiple gifs just wont show at all when rebooting, just the molecule model shows up like usual (possibly size related, the rcf ends up being around 80 megabytes). Tried 2 other, smaller gifs and both have led to bootloops. Below is the gif I want to use but it wont appear regardless of what settings/changes i apply when turning it into an rcf file
![boot_animation](https://user-images.githubusercontent.com/87270756/125198707-147ddd80-e231-11eb-8958-01d250b3f263.gif)

**Comment by SKGleba** [comment]
Anything above 32MBs (realistically 16) will not be loaded to memory due to memory limitations for kernel, and anyways it is not recommended to have such heavy gifs because the system may just crash at boot (not loop the gif to infinity but crash reboot).

Bootloops cause is currently unknown, it seems to happen less with a higher thread priority. It may also be related to the GPU module failing to initialize because of the constant framebuffer updates.

Overall id recommend using lightweight/simple animations a'la android or CBS-Manager in liveread mode (but the frame rate drops drastically).

**Comment by SKGleba** [comment]
About loops please continue in https://github.com/SKGleba/VitaTools/issues/3

**Comment by SKGleba** [comment]
v1.1 has support for up to 112MiB, but please note that it takes a while to load such huge files to memory
