### ISSUE TITLE
[VITA-BOOTANIM] mkanim not properly make rcf animation

### ISSUE THREAD

**Issue by TheMerret** [SKGleba/VitaTools#8]
converting boot_animation.gif to a supported gif type...
    extracting gif frames...
    converting frames to RGBA...
    compressing frames...
    gzip: invalid option -- k
    Try 'gzip --help' for more information.
    gzip: invalid option -- k
    Try 'gzip --help' for more information.
    gzip: invalid option -- k
    [...]
    all done!
I removed "-k" option  in **mkanim.c:120** and **mkanim.c:126** and it's working fine for me

**Comment by TheMerret** [comment]
gzip 1.3.12 error

**Comment by ilylily** [comment]
got this as well on OpenBSD, whose gzip doesn't have the keep flag. a better solution to this is replacing `-k %s` with `-k < %s > %s.gz` and adding a second `file_name` arg. this maintains the original functionality and improves portability

but since two lines later there's `unlink(file_name)`, removing `-k` as well as the unlink line might be best. gzip itself removes the original file and all seems well on my end

**Comment by SKGleba** [comment]
Weird.
Yeah the -k was kept for debug purposes, i will remove it.
